// Code generated by MockGen. DO NOT EDIT.
// Source: TamaskaWaterManagement/pkg/json (interfaces: JSON)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockJSON is a mock of JSON interface.
type MockJSON struct {
	ctrl     *gomock.Controller
	recorder *MockJSONMockRecorder
}

// MockJSONMockRecorder is the mock recorder for MockJSON.
type MockJSONMockRecorder struct {
	mock *MockJSON
}

// NewMockJSON creates a new mock instance.
func NewMockJSON(ctrl *gomock.Controller) *MockJSON {
	mock := &MockJSON{ctrl: ctrl}
	mock.recorder = &MockJSONMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJSON) EXPECT() *MockJSONMockRecorder {
	return m.recorder
}

// Marshal mocks base method.
func (m *MockJSON) Marshal(arg0 interface{}) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Marshal", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Marshal indicates an expected call of Marshal.
func (mr *MockJSONMockRecorder) Marshal(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Marshal", reflect.TypeOf((*MockJSON)(nil).Marshal), arg0)
}

// Unmarshal mocks base method.
func (m *MockJSON) Unmarshal(arg0 []byte, arg1 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unmarshal", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unmarshal indicates an expected call of Unmarshal.
func (mr *MockJSONMockRecorder) Unmarshal(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unmarshal", reflect.TypeOf((*MockJSON)(nil).Unmarshal), arg0, arg1)
}
